volumes:
  mongo-data:

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INIT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INIT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INIT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INIT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INIT_USERNAME}:${MONGO_INIT_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  
  redis:
    image: redis
    restart: always
    ports:
      - 6380:6379